version: "3.7"

services:
  backend:
    build:
      context: app
      dockerfile: DockerfileProd
    env_file:
      - .env.backend.prod
    depends_on:
      - db
    ports:
      - 80:8080

  db:
    build:
      context: postgres
      dockerfile: DockerfileProd
    env_file:
      - .env.db.prod
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  pg_data: